stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd docker
    - docker compose -f docker-compose.yml pull --quiet
    - docker compose -f docker-compose.yml down
    - docker compose -f docker-compose.yml up -d
    - docker system prune -a --force
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - deploy-system
  only:
    - main
