services:
  nginx:
    image: nginx:1.25.3-bookworm
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "0.0.0.0:80:80"

networks:
  web:
    external: true
