services:
  host:
    image: registry.gitlab.com:${CI_PIPELINE_ID}
    container_name: "frontend"
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.frontend.rule=Host(`frontend.com`)"
      - "traefik.http.routers.frontend.entrypoints=http,https"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    # mem_limit: 124

networks:
  web:
    external: true
